const flock = [];

// let alignSlider, cohesionSlider, separationSlider;

var nomes = [
  "Felipe Santi",
  "Adriane Kirst",
  "Alain Quemin",
  "Aleandro Mushina",
  "Alex Wayyorer",
  "Alexandre Augusto Oliveira",
  "Alexandre Basso",
  "Alexandre Chaves",
  "Alexandre Costa Cordeiro",
  "Alexandre Neumayv",
  "Alexis Ouellet",
  "Aline Gomes Lipareli",
  "Aline Haag",
  "Álvaro De Azevedo Diaz",
  "Amanda Domingos",
  "Amanda Guedes",
  "Amanda Kruger",
  "Amanda Pimenta Faria",
  "Ana Letícia Fialho",
  "Ana Luíza de Melo Albuquerque",
  "Ana Paula K Soares",
  "Anderson Ferrari",
  "Anderson Sávio Ferreira",
  "André Felipe De A. Ferraro",
  "André Ferreira Martins",
  "André Godoy",
  "André Parente",
  "Andrea Hellena dos Santos",
  "Andreía Corazzini",
  "Andressa Muni",
  "Andrey Kasay",
  "Angélica de Moraes",
  "Angelita Cardoso",
  "Angella Conte",
  "Angelo Maragno",
  "Anthony Rousseau",
  "Antonella Iamariulli",
  "Antonio Bandeira",
  "Antonio Carlos Picalho",
  "Anushka Vema",
  "Arthur F Flores Duarte",
  "Augu Alenc",
  "Ayao Okamoto",
  "Barabás Lőrinc",
  "Beatriz Ribeiro Gomes",
  "Benedito Costa",
  "Bento Ribeiro B`Ro",
  "Betânia Silveira",
  "Bettina Vaz Guimarães",
  "Bianca Halaseh",
  "Bianca Scliar",
  "Bianca Tomaselli",
  "Bil Lühmann",
  "Bruna Kassab",
  "Bruna Ribeiro",
  "Bruna Schenkel",
  "Bruno Bez",
  "Bruno Castilho",
  "Bruno Gondim Luna",
  "Bruno Ibias",
  "Bruno Muller",
  "Caio Fazolin",
  "Caio L. Gandolfi",
  "Caio Villa de Lima",
  "Camila Argenta",
  "Camila Kressin",
  "Camille St Martin",
  "Candas Sisman",
  "Carina Emanuelli",
  "Carla Dellagerisi",
  "Carla Linhares",
  "Carlo Alberto Rusca",
  "Carlos Camppelini",
  "Carlos Toledo",
  "Carol Garlet",
  "Carol Krügel",
  "Carolina Berger",
  "Carolina De Oliveira Camison",
  "Christian Teria",
  "Christine Greiner",
  "Christopher Coleman",
  "Clarissa Alcântara",
  "Clarissa Gianni",
  "Clau Paranhos",
  "Claudia Alexandra",
  "Claudia Cárdenas",
  "Cláudia Carpinelli",
  "Cláudio Gonçalves Brandão",
  "Cleci Rocha Martins",
  "Alê Abreu",
  "Álvaro H. Fieri",
  "Conrado Buhrer",
  "Cristina Luviza Battiston",
  "Cyntia Werner",
  "Daniel de Souza Severo",
  "Daniel Florencio",
  "Daniela Maria",
  "Daniela Vicentini",
  "Daniele Gonçalves de Freitas Paulino",
  "Danilo Barretto",
  "David Adler",
  "David Radparvar",
  "Débora Mendes Nunes Jank",
  "Denis Timko",
  "Denise Rogenski Raizel",
  "Diana Chiodelli",
  "Diego de los Campos",
  "Diego Veri",
  "Diogo de haro",
  "Bárbara Brum",
  "Dominique Kaplowtiz",
  "Douglas Everton Etges",
  "Duo Strangloscope",
  "Dylan Carter",
  "Ébano Machado Piacentini",
  "Edelita Moreira Anania",
  "Eduarda Silveira Ritzmann Alexandre",
  "Eduardo Cacavalcanti",
  "Eduardo Cristiano Negrão",
  "Eduardo Menezes",
  "Eduardo Ventura",
  "Elisa Rusca",
  "Evamm",
  "Evandro Carreira",
  "Evandro Machado",
  "Eve Machado",
  "Fabiana Wielewicki",
  "Fábio Ape",
  "Fabio Berger",
  "Fábio Machado",
  "Fábio Noronha",
  "Fabrizio Postiglione",
  "Fê Luz",
  "Felipe Bassi",
  "Felipe Gonçalves Felice",
  "Felipe Mesquita",
  "Felipe Rosene Klapsztein",
  "Fellipe dos Santos",
  "Fer Pietra",
  "Fernanda Lago",
  "Fernanda Valadares",
  "Fernando C N Brizola",
  "Fernando Correa",
  "Fernando Espíndola",
  "Fernando Velázquez",
  "Flávia Klein",
  "Flora Holderbaum",
  "Fran Bitten",
  "Francielle R. Souza",
  "Francine Goudel",
  "Francis Silva",
  "Gabriel Carvalho",
  "Gabriel Gariba",
  "Gabriel Guaraciaba",
  "Gabriel Rodrigues da Costa Noel",
  "Gabriela Cabral",
  "Gabriela Comassetto Fernandez",
  "Gabriela De Oliveira Curlotto",
  "Gabriela Delcin Pires",
  "Gabriela Dreher",
  "Gabriele Gomes",
  "Gala Ivannikova",
  "Gero Doll",
  "Gi Pagotto",
  "Giba Duarte",
  "Giulia Ciprandi",
  "Glaucis de Morais",
  "Glerison Zart",
  "Grupo Borra",
  "Guilherme Polidoro",
  "Guilherme Schneider",
  "Guillaume Passinay",
  "Gustavo Brazzalle",
  "Guto Alencar",
  "Guto Lacaz",
  "Hale Schneider",
  "Helena Fretta",
  "Heleno Bernardi",
  "Holger Beier",
  "Iam Campigotto",
  "Idair Martins Junior",
  "Ighor Duarte",
  "Ignazio Lucenti",
  "Igor Minatto",
  "Inge Madden",
  "Isabelle Prates Cordeiro Bhering",
  "Isis Machado Silva",
  "Jaicle Melo",
  "Jan Felix - Koeppen",
  "Jane Lecardelli",
  "Janga",
  "Jeff Nefferkturu",
  "Jennifer Oliver",
  "Jessica Marati Radparvar",
  "Jim Avignon",
  "Joana Brum",
  "Joana Vasconcelos",
  "João Aires",
  "João Luiza da Rosa",
  "João Lurdaros",
  "João Ricardo Mattos",
  "João Salvador",
  "Johan Rijpma",
  "Jordi Piera",
  "José Carlos Rovai Filho",
  "José Faria",
  "José Luiz Pellegrin",
  "José Miguel Wisnik",
  "José Valério Dos Santos Neto",
  "Julia Amaral",
  "Julia Bertoleto",
  "Júlia Hoffmann",
  "Júlia Thomé",
  "Juliana Crispe",
  "Juliana Hoffmann",
  "Juliana Santana",
  "Juliana Stringhini",
  "Juliano Poeta",
  "Kadu Szili",
  "Kamilla Nunez",
  "Karim Rojas",
  "Karina Mariane Apolinario Negrão",
  "Karina Zen",
  "Karoline Alves",
  "Katia Maciel",
  "Kauê Cano Souza",
  "Kaue Costa",
  "Kauê Policastro",
  "Kevin McGloughlin",
  "Kika Nicolela",
  "Laïs Krücken",
  "Lais Silveira Santos",
  "Laleska Lebioda",
  "Lara Noroes Albuquerque",
  "Laura De Oliveira Pinto Coelho",
  "Leila Pessoa",
  "Leonardo Carlos Penna",
  "Leonardo Ostan",
  "Lese Pierre de Lima",
  "Letícia Cardoso",
  "Leticia Corrêa",
  "Leticia Kapper",
  "Lia Mattos",
  "Liana Domeneghim Chiaradia",
  "Liandra Araujo Resner",
  "Ligia Jahn",
  "Ligia Moreiras",
  "Lilian Barbon",
  "Liz Schumacker Freitas",
  "Love Love 6",
  "Lucas Baranowski",
  "Lucas Gehre",
  "Lucas Leandro",
  "Lucia Helena Teles",
  "Luciana Ozório",
  "Luciana Petrelli",
  "Lucila Vilela",
  "Luisa Pfitzer Wolf",
  "Luiz Rosa",
  "Luiza Lins",
  "Luiza Giordano",
  "Luíza Monte Blanco",
  "Luize Rosa Zanette",
  "Luize Zanette",
  "Luzia Cristina Oliveira Coqueiro Alves",
  "Magali",
  "Maiana Perdomo",
  "Manuela de Souza Merigo",
  "Manuela Pammerihn Vitiello",
  "Manuela Valls",
  "Marcelo Mello de Souza",
  "Marcelo Schlee",
  "Márcia Maria de Oliveira Ramos",
  "Marcia Regina Seva",
  "Marcio H Mota",
  "Marcos Sari",
  "Marcos Serafim",
  "Marcos Valinio de Castro Junior",
  "Marcos Walickosky",
  "Marcus Frugoli",
  "Maria Angela Biscaia",
  "Maria Clara Reschke",
  "Maria Isilda Rosa",
  "Maria Julia Capelato",
  "Maria Lucia Zanaco Tureck",
  "Mariana Alexandre Bandeira",
  "Mariana Levy Piza Fontes",
  "Mariana Silva da Silva",
  "Marin Vesely",
  "Marina Kurth Kinas",
  "Marina Moros",
  "Marina Tavares",
  "Mario Schuster",
  "Mário Sérgio Oliveira",
  "Marisa Montalvo",
  "Marta Machado",
  "Marta Martins",
  "Maryana Patricia Folis",
  "Mathew",
  "Maurício Afonso",
  "Maxime Causeret",
  "Mazu Prozak",
  "Meg Rousenque",
  "Melissa Ferreira",
  "Midil Siqueira Cima",
  "Mike Hallett",
  "Mimi the Clown",
  "Monica Siedler",
  "Monique Szpoganicz",
  "Morgan Beringer",
  "Moysés Alencar de Carvalho",
  "Muriel Paraboni",
  "Murilo Guindani",
  "Myrine Vlavianos",
  "Nadja Aires",
  "Natalia Brasil",
  "Natalia Rumpf",
  "Natalia Seeger Duarte",
  "Natássia Lisboa",
  "Nathalia Pires da Silveira",
  "Nekane Rivas",
  "Nicole Byer",
  "Nina Pinho",
  "Octávio Brandão Richter",
  "Olivia Dias Bagott",
  "Ölveti Mátyás",
  "Osmar Domingos",
  "Otto Guerra",
  "Pablo Del Rio",
  "Pablo Macaya Vazquez",
  "Pablo Paniagua",
  "Paul Dinning",
  "Paula Caroline Da Silva",
  "Paula Guimarães",
  "Pauli Cakes",
  "Paulinho Rossatto",
  "Paulo Abarno",
  "Paulo Gaiad",
  "Paulo Greuel",
  "Paulo Henrique Silva",
  "Pedro Cavalcante",
  "Pedro Franz",
  "Priscila Thomas Pinheiro",
  "Rafael Alves",
  "Rafael Augusto Menezes Lohmann",
  "Rafael Bomaro Ferreira",
  "Rafael Prim",
  "Rafael Strangloscópico",
  "Rafaela Helbing de Oliveira",
  "Raquel Stolf",
  "Raúl Caudillo",
  "Regina Parra",
  "Rejane Brayer",
  "Renan Alvves Fonseca",
  "Renato Cotrin Maciel",
  "Ricardo Alexandro Werlich",
  "Ricardo Mello",
  "Roberta Carvalho",
  "Roberta Pimentel",
  "Roberta Tassinari",
  "Rodrigo Braga",
  "Rodrigo Cunha",
  "Rodrigo Montandon Born",
  "Rodrigo Perez",
  "Rodrigo Porto Santos",
  "Rodrigo Ramos",
  "Rodrigo Roncaglio",
  "Rosana Cacciatora",
  "Rubens Oestroem",
  "Sabrina Hanich",
  "Sandra Alves",
  "Sandra Makowiecky",
  "Sandro Alexandre Salles",
  "Sávio Leite",
  "Sebastian Van Kuyk",
  "Sergio Reis",
  "Sharon Elizabeth",
  "Shiras Moose",
  "Sidan Orafa",
  "Silva Carvalho",
  "Silvana Frate",
  "Silvana Leal",
  "Silvana Macedo",
  "Silvia Carvalho",
  "Silvia Lazzaretti",
  "Silvia Nella Istre",
  "Simone Bobsin",
  "Soninha Vill",
  "Soroush Pooy",
  "Steevens Simeon",
  "Stephen Trevor Guilday",
  "Sulio Rovai Neto",
  "Talita de Carvalho",
  "Teresa Siewerdt",
  "Thaís R. Nolasco de Souza",
  "Theodora Martins",
  "Thiago Goldfeder Krieck",
  "Thiago Ninomiya",
  "Thomas Israel",
  "Tiago Brizolara",
  "Tiago Rabelo Melo",
  "Tiago Rivaldo",
  "Tiago Silveira da Silva",
  "Tropicalistas",
  "Troy Arie Cobb",
  "Troy Erstling",
  "Tunga",
  "Vanessa Neuber",
  "Vanessa O Kanaan",
  "Vigas",
  "Violeta Sutili",
  "Viviana Lopes Bagé",
  "Walmor de Oliveira",
  "Wander Levi",
  "Weber Simoes Oliveira",
  "Wladymir Lima",
  "Wolfgang Lehmann",
  "Xavier Chassaing",
  "Yara Guasque",
  "Zach Barney",
  "Zé Kielwagen",
  "Zenilda Cardoso",
  "Shortcup",
  "Vinz",
  "Hencke",
  "Fabio Ape",
  "Eduardo Abraham",
  "Murilo",
  "Ruan Fracik",
  "Doriva Roze",
  "Rafael Teixeira",
  "Edo",
  "Caetano",
  "Guto",
  "ORDEEP",
  "Marie Painní",
  "Milidiu",
  "Quest",
  "Henrique Vieceli",
  "Bruna Moura",
  "Daniel Dumach",
  "Evan Baggs",
  "Jean Mafra",
  "Konnin",
  "Kosmo",
  "Pesco",
  "Markus Sommer",
  "Fred P",
  "Daniel Bell",
  "Diogo de Haro",
  "Rafael Augusto",
  "Serigio Bello"
];

function setup() {
  createCanvas(displayWidth, displayHeight);
  // alignSlider = createSlider(0, 2, 1.5, 0.1);
  // cohesionSlider = createSlider(0, 2, 1, 0.1);
  separationSlider = createSlider(0, 2, 2, 0.1);
  for (let i = 0; i < nomes.length; i++) {
    flock.push(new Boid(nomes[i]));
  }
}

function draw() {
  background(0);
  textFont("Montserrat");
  textSize(18);
  fill(255, 255, 255);
  // opacity(0.5);
  for (let boid of flock) {
    boid.edges();
    boid.flock(flock);
    boid.update();
    boid.show();
  }
}
